name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ruby:
    name: "Test Backend (Jekyll ${{ matrix.jekyll_version }}, Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll_version }}
      JEKYLL_LOG_LEVEL: warn
      RACK_ENV: test
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.3"]
        jekyll_version:
          - "~> 3.9"
          - "~> 4.0"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Unit Tests
        run: bundle exec rspec --format documentation --force-color --backtrace

  node:
    name: "Test Frontend (Node ${{ matrix.node_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        node_version: ["20"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: "Set up Node ${{ matrix.node_version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install
      - name: Run tests and build frontend
        run: bash script/build
